### PR TITLE
Eyeball changes to BSP usage

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Hi Craig.  The purpose of this pull-request is to ask you for a review of changes I made to core-v-verif to better use your BSP.   I want to ensure I've got it right.   I did a couple of things:

1. Renamed the crt0.S, link.ld, etc. in cv32/tests/core/asm and  cv32/tests/core/custom to ensure they are not being used.  Note that I determined that the misalign tests uses cv32/tests/core/custom/startup/support.h.  I'm not sure if this is something we should be supporting in the BSP or not.

2. Modified targets to make the elf files from both C (%.elf: %.c) or Assembly (%.elf: %.S) sources.  This means we do not need one-target-per-test.  I am reasonably confident of the C rule, but not for the Assembly rule.

The targets below all compile and run.  The hello-world program should probably be fixed and replace your bsp-example-veri-run target.   The command (CUSTOM_PROG=riscv_ebreak_test_0) is the only example I made of an Assembly run.  I am not convinced it does anything real.

Assuming this is all working as expected (the C programs do anyway), this is a big step as all the targets below use your BSP.  This is HUGE!   If you could review to ensure I'm doing this as you'd expect, that would be appreciated.

```
make clean_all
make
make bsp-example-veri-run
make custom CUSTOM_PROG=dhrystone
make custom CUSTOM_PROG=misalign
make custom CUSTOM_PROG=fibonacci
make custom CUSTOM_PROG=illegal
make custom CUSTOM_PROG=riscv_ebreak_test_0
```

### CODE REVIEW

**Comment by craigblackmore** [comment]
Hi Mike. It's great to see how much this has simplified the makefile.

1. `misalign.c` doesn't need to include support.h as it doesn't seem to use it anywhere. It looks like `cv32/tests/core/custom/startup/support.h` is only used by `cv32/tests/core/custom/startup/start.S`, which in turn does not appear to be used by anything.

2. The assembly rule looks fine, but `riscv_ebreak_test.S` defines its own startup code and exception handlers and is not using the bsp (except for the linker script). Writing an assembly test that uses the full bsp should be a case of defining a `main` function in your assembly file and leaving the startup, vector table, exception handling to the bsp.

**Comment by MikeOpenHWGroup** [comment]
That assembly program, `riscv_ebreak_test.S` was included because it is a generated file that is representative of most of the code that we will be pushing through the testbench.  These test-programs will typically contain their own startup code and exception handlers, and will only need our linker script.

I'm in the process of rationalizing all of this for both of our simulation testbenches.  Let's keep this PR "alive" until then.

**Comment by MikeOpenHWGroup** [comment]
OK, I've spent a fun few hours with the BSP and the `core` testbench.   My goal was to get all tests running with the BSP, but this failed.   Have a look at `cv32/sim/core/README.md` for a list of targets that run tests using Verilator.   These all use the BSP.

The test-programs we obtained from the RISC-V Compliance group do not seem to be able to run using the BSP.  The target to see this is `make cv32-riscv-tests`.  Using the BSP's linker gets the program stuck in an endless loop complaining about no exception handler.

I did note that the cv32-riscv-tests wants a symbol for `__bss_end`.  The BSP linker has `__bss_start` and `__BSS_END__`.  Remaining this last symbol to `__bss_end` means that the cv32-riscv-tests compiles, and none of the other test-programs are affected.  Let me know if that change breaks anything.

**Comment by MikeOpenHWGroup** [comment]
Last comment of the day... just FYI, I was able to run the BSP using the UVM environment with no issues other than the ones listed above (the core testbench and UVM environment both use the same BSP and same memory model, so that was expected).   The UVM memory need to have a parameter updated to match the memory size to the BSP, but that was trivial.

**Comment by craigblackmore** [comment]
Renaming to `__bss_end` is fine as nothing depends on `__BSS_END__`. The upstream linker script has `__bss_start` / `__BSS_END__` and my approach was to start with that script and make the minimal changes required for core-v.

Looks good to me.

**Pull request merged**
